/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Desk(props) {
  const { nodes, materials } = useGLTF('/desk.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.31, 0.08, -1.96]} rotation={[-Math.PI / 2, 0, 0.74]} scale={1.23}>
        <mesh geometry={nodes.Mesh_0.geometry} material={materials.wire9008136} />
        <mesh geometry={nodes.Mesh_1.geometry} material={materials.wireW225087} />
        <mesh geometry={nodes.Mesh_10.geometry} material={materials.Piel} />
        <mesh geometry={nodes.Mesh_11.geometry} material={materials.Piel} />
        <mesh geometry={nodes.Mesh_12.geometry} material={materials.Plastico_032negro} />
        <mesh geometry={nodes.Mesh_13.geometry} material={materials.Plastico_032negro} />
        <mesh geometry={nodes.Mesh_14.geometry} material={materials.Plastico_032negro} />
        <mesh geometry={nodes.Mesh_15.geometry} material={materials.Plastico_032negro} />
        <mesh geometry={nodes.Mesh_16.geometry} material={materials.Plastico_032negro} />
        <mesh geometry={nodes.Mesh_17.geometry} material={materials.Plastico_032negro} />
        <mesh geometry={nodes.Mesh_18.geometry} material={materials.Plastico_032negro} />
        <mesh geometry={nodes.Mesh_19.geometry} material={materials.Plastico_032negro} />
        <mesh geometry={nodes.Mesh_2.geometry} material={materials.wireX199225} />
        <mesh geometry={nodes.Mesh_20.geometry} material={materials.Plastico_032negro} />
        <mesh geometry={nodes.Mesh_21.geometry} material={materials.Plastico_032negro} />
        <mesh geometry={nodes.Mesh_22.geometry} material={materials.Plastico_032negro} />
        <mesh geometry={nodes.Mesh_23.geometry} material={materials.Plastico_032negro} />
        <mesh geometry={nodes.Mesh_24.geometry} material={materials.Plastico_032negro} />
        <mesh geometry={nodes.Mesh_25.geometry} material={materials.Plastico_032negro} />
        <mesh geometry={nodes.Mesh_26.geometry} material={materials.Plastico_032negro} />
        <mesh geometry={nodes.Mesh_27.geometry} material={materials.Plastico_032negro} />
        <mesh geometry={nodes.Mesh_28.geometry} material={materials.Plastico_032negro} />
        <mesh geometry={nodes.Mesh_29.geometry} material={materials.Plastico_032negro} />
        <mesh geometry={nodes.Mesh_3.geometry} material={materials.wire_140088225} />
        <mesh geometry={nodes.Mesh_30.geometry} material={materials.Plastico_032negro} />
        <mesh geometry={nodes.Mesh_31.geometry} material={materials.Plastico_032negro} />
        <mesh geometry={nodes.Mesh_32.geometry} material={materials.Plastico_032negro} />
        <mesh geometry={nodes.Mesh_33.geometry} material={materials.Plastico_032negro} />
        <mesh geometry={nodes.Mesh_34.geometry} material={materials.wire_140088225} />
        <mesh geometry={nodes.Mesh_4.geometry} material={materials.MEtal_032cromo} />
        <mesh geometry={nodes.Mesh_5.geometry} material={materials.MEtal_032cromo} />
        <mesh geometry={nodes.Mesh_6.geometry} material={materials.MEtal_032cromo} />
        <mesh geometry={nodes.Mesh_7.geometry} material={materials.MEtal_032cromo} />
        <mesh geometry={nodes.Mesh_8.geometry} material={materials.Piel} />
        <mesh geometry={nodes.Mesh_9.geometry} material={materials.Piel} />
      </group>
      <group position={[0.11, 0.91, -2.65]} rotation={[Math.PI, -1.55, Math.PI]} scale={0.09}>
        <group position={[-0.93, 4.94, 0.06]} rotation={[0, 0, 0.12]} scale={[0.26, 7.46, 15.13]}>
          <mesh geometry={nodes.Curved_Monitor_MAT_Plastic_0.geometry} material={materials.MAT_Plastic} />
          <mesh geometry={nodes.Curved_Monitor_MAT_Screen_0.geometry} material={materials.MAT_Screen} />
        </group>
        <group position={[0.08, 0, 0]}>
          <mesh geometry={nodes.Peana_MAT_Plastic_0.geometry} material={materials.MAT_Plastic} position={[-2.98, 0, 0.06]} />
        </group>
      </group>
      <group position={[-1.11, 0.89, -2.49]} scale={0.02}>
        <mesh geometry={nodes.pCylinder1_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCylinder1_lambert4_0.geometry} material={materials.lambert4} />
        <mesh geometry={nodes.polySurface7_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <group position={[-0.99, 0.89, -2]} rotation={[-0.05, 0.72, 0.06]} scale={0}>
        <group position={[40.84, 6.45, -36.65]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.bottombuttons_ultrablack_0001.geometry} material={materials.ultrablack} />
        </group>
        <group position={[-41.09, 6.45, -36.65]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.bottombuttons001_ultrablack_0001.geometry} material={materials.ultrablack} />
        </group>
        <group position={[-43.19, 25.41, -23.14]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.73, 1.73, 0.5]}>
          <mesh geometry={nodes.Box001_clear_0001.geometry} material={materials.clear} />
        </group>
        <group position={[-43.19, 25.41, -8]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={[1.73, 1.73, 0.5]}>
          <mesh geometry={nodes.Box002_clear_0001.geometry} material={materials.clear} />
        </group>
        <group position={[-50.76, 25.41, -15.57]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[1.73, 1.73, 0.5]}>
          <mesh geometry={nodes.Box003_clear_0001.geometry} material={materials.clear} />
        </group>
        <group position={[-35.63, 25.41, -15.57]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[1.73, 1.73, 0.5]}>
          <mesh geometry={nodes.Box004_clear_0001.geometry} material={materials.clear} />
        </group>
        <group position={[-32.27, 26.37, -31.56]} rotation={[-1.77, 0, 0]} scale={[1, 1, 0.56]}>
          <mesh geometry={nodes['Box005_11_-_Default_0001'].geometry} material={materials['11_-_Default']} />
        </group>
        <group position={[42.71, 23.08, -25.44]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.93, 0.93, 1.01]}>
          <mesh geometry={nodes.Cylinder001_clear_0001.geometry} material={materials.clear} />
        </group>
        <group position={[42.71, 23.08, -5.73]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.93, 0.93, 1.01]}>
          <mesh geometry={nodes.Cylinder002_clear_0001.geometry} material={materials.clear} />
        </group>
        <group position={[33.28, 23.08, -15.73]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[0.93, 0.93, 1.01]}>
          <mesh geometry={nodes.Cylinder003_clear_0001.geometry} material={materials.clear} />
        </group>
        <group position={[52.41, 23.08, -15.73]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[0.93, 0.93, 1.01]}>
          <mesh geometry={nodes.Cylinder004_clear_0001.geometry} material={materials.clear} />
        </group>
        <group position={[21.02, 27.17, 4.47]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.51, 1.51, 2.42]}>
          <group position={[0, 0, -2.62]}>
            <mesh geometry={nodes['Cylinder005_10_-_Default_0001'].geometry} material={materials['10_-_Default']} />
            <mesh geometry={nodes.Cylinder005_ultrablack_0001.geometry} material={materials.ultrablack} />
          </group>
        </group>
        <group position={[-20.82, 27.17, 4.47]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.51, 1.51, 2.42]}>
          <group position={[0, 0, -2.62]}>
            <mesh geometry={nodes['Cylinder006_10_-_Default_0001'].geometry} material={materials['10_-_Default']} />
            <mesh geometry={nodes.Cylinder006_ultrablack_0001.geometry} material={materials.ultrablack} />
          </group>
        </group>
        <group position={[21.07, 34.69, 4.49]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.12, 1.12, 0.23]}>
          <mesh geometry={nodes.Cylinder007_rubber_0001.geometry} material={materials.rubber} />
        </group>
        <group position={[-20.86, 34.69, 4.49]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.12, 1.12, 0.23]}>
          <mesh geometry={nodes.Cylinder008_rubber_0001.geometry} material={materials.rubber} />
        </group>
        <group position={[-0.06, 18.35, 5.65]} rotation={[-Math.PI / 2, 0, 0]}>
          <group position={[29.94, -0.09, -3.71]}>
            <mesh geometry={nodes['Plane002_10_-_Default_0001'].geometry} material={materials['10_-_Default']} />
            <mesh geometry={nodes['Plane002_11_-_Default_0001'].geometry} material={materials['11_-_Default']} />
            <mesh geometry={nodes['Plane002_16_-_Default_0001'].geometry} material={materials['16_-_Default']} />
            <mesh geometry={nodes.Plane002_standard_steel_0001.geometry} material={materials.standard_steel} />
            <mesh geometry={nodes.Plane002_ultrablack_0001.geometry} material={materials.ultrablack} />
          </group>
        </group>
        <group position={[41.14, 19.12, -38.6]} rotation={[-Math.PI / 2, 0, 0]}>
          <group position={[-10.36, -45.18, -4.48]}>
            <mesh geometry={nodes.topbuttons_ultrablack_0001.geometry} material={materials.ultrablack} />
          </group>
        </group>
        <group position={[-41.22, 19.12, -38.6]} rotation={[-Math.PI / 2, 0, 0]}>
          <group position={[-10.36, -45.18, -4.48]}>
            <mesh geometry={nodes.topbuttons001_ultrablack_0001.geometry} material={materials.ultrablack} />
          </group>
        </group>
        <group position={[-0.06, 22.22, -26.99]} rotation={[-Math.PI / 2, 0, 0]}>
          <group position={[29.94, -31.78, -7.04]}>
            <mesh geometry={nodes['touchpad_11_-_Default_0001'].geometry} material={materials['11_-_Default']} />
          </group>
        </group>
      </group>
      <group position={[1.47, 0.91, -2.18]} rotation={[Math.PI, -0.92, Math.PI]} scale={0.09}>
        <group position={[-0.93, 4.94, 0.06]} rotation={[0, 0, 0.12]} scale={[0.26, 7.46, 15.13]}>
          <mesh geometry={nodes.Curved_Monitor_MAT_Plastic_0001.geometry} material={materials['MAT_Plastic.001']} />
          <mesh geometry={nodes.Curved_Monitor_MAT_Screen_0001.geometry} material={materials['MAT_Screen.001']} />
        </group>
        <group position={[0.08, 0, 0]}>
          <mesh geometry={nodes.Peana_MAT_Plastic_0001.geometry} material={materials['MAT_Plastic.001']} position={[-2.98, 0, 0.06]} />
        </group>
      </group>
      <mesh geometry={nodes.Desktop.geometry} material={materials['Material.001']} position={[0.21, 0.81, -2.34]} scale={[1.76, 1.08, 0.65]} />
      <group position={[-0.13, 0.89, -2.15]} rotation={[Math.PI / 2, 0, 0]} scale={[0.02, 0.02, 0.01]}>
        <mesh geometry={nodes.Mesh.geometry} material={materials.blinn1} />
        <mesh geometry={nodes.Mesh_35.geometry} material={materials.blinn2} />
      </group>
    </group>
  )
}

useGLTF.preload('/desk.glb')
